"""create payroll domain schema

Revision ID: 85c912f8220e
Revises: 
Create Date: 2026-07-24 15:08:29.185002
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '85c912f8220e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employees',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('employee_code', sa.String(length=24), nullable=False),
    sa.Column('department', sa.String(length=80), nullable=False),
    sa.Column('job_title', sa.String(length=120), nullable=False),
    sa.Column('job_grade', sa.String(length=20), nullable=False),
    sa.Column('location', sa.String(length=80), nullable=False),
    sa.Column('annual_salary', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('hire_date', sa.Date(), nullable=False),
    sa.Column('termination_date', sa.Date(), nullable=True),
    sa.Column('employment_status', sa.Enum('active', 'terminated', 'leave', name='employmentstatus', native_enum=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('annual_salary >= 0', name='ck_employee_salary_nonnegative'),
    sa.CheckConstraint('termination_date IS NULL OR termination_date >= hire_date', name='ck_employee_termination_after_hire'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_code')
    )
    op.create_index('ix_employees_department_grade', 'employees', ['department', 'job_grade'], unique=False)
    op.create_table('model_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('model_name', sa.String(length=80), nullable=False),
    sa.Column('model_version', sa.String(length=40), nullable=False),
    sa.Column('trained_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('training_period_start', sa.Date(), nullable=False),
    sa.Column('training_period_end', sa.Date(), nullable=False),
    sa.Column('feature_names', sa.JSON(), nullable=False),
    sa.Column('parameters', sa.JSON(), nullable=False),
    sa.Column('metrics', sa.JSON(), nullable=False),
    sa.Column('artifact_path', sa.String(length=260), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payroll_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('payment_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'processed', 'closed', name='payrollrunstatus', native_enum=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('payment_date >= period_start', name='ck_payroll_run_payment_date'),
    sa.CheckConstraint('period_end >= period_start', name='ck_payroll_run_period'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('period_start', 'period_end', name='uq_payroll_run_period')
    )
    op.create_table('bank_account_history',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('employee_id', sa.String(length=36), nullable=False),
    sa.Column('account_token', sa.String(length=64), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('changed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('change_reason', sa.String(length=120), nullable=True),
    sa.CheckConstraint('effective_to IS NULL OR effective_to >= effective_from', name='ck_bank_account_effective_range'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id', 'account_token', 'effective_from', name='uq_bank_account_version')
    )
    op.create_index('ix_bank_account_employee_effective', 'bank_account_history', ['employee_id', 'effective_from'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('payment_reference', sa.String(length=40), nullable=False),
    sa.Column('employee_id', sa.String(length=36), nullable=False),
    sa.Column('payroll_run_id', sa.String(length=36), nullable=False),
    sa.Column('base_pay', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('overtime_pay', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('bonus_pay', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('gross_pay', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('income_tax', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('national_insurance', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('pension', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('other_deductions', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_deductions', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('net_pay', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('bank_account_token', sa.String(length=64), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('base_pay >= 0', name='ck_payment_base_pay'),
    sa.CheckConstraint('gross_pay >= 0', name='ck_payment_gross_pay'),
    sa.CheckConstraint('total_deductions >= 0', name='ck_payment_deductions'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['payroll_run_id'], ['payroll_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('payment_reference')
    )
    op.create_index('ix_payments_bank_token', 'payments', ['bank_account_token'], unique=False)
    op.create_index('ix_payments_employee_run', 'payments', ['employee_id', 'payroll_run_id'], unique=False)
    op.create_table('anomaly_alerts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('payment_id', sa.String(length=36), nullable=False),
    sa.Column('model_run_id', sa.String(length=36), nullable=True),
    sa.Column('source', sa.Enum('rule', 'model', 'hybrid', name='alertsource', native_enum=False), nullable=False),
    sa.Column('rule_code', sa.String(length=80), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('risk_level', sa.Enum('low', 'medium', 'high', 'critical', name='risklevel', native_enum=False), nullable=False),
    sa.Column('summary', sa.String(length=300), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum('open', 'in_review', 'resolved', name='alertstatus', native_enum=False), nullable=False),
    sa.Column('detector_version', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('risk_score >= 0 AND risk_score <= 1', name='ck_alert_risk_score'),
    sa.ForeignKeyConstraint(['model_run_id'], ['model_runs.id'], ),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_alerts_payment', 'anomaly_alerts', ['payment_id'], unique=False)
    op.create_index('ix_alerts_status_risk', 'anomaly_alerts', ['status', 'risk_level'], unique=False)
    op.create_table('anomaly_labels',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('payment_id', sa.String(length=36), nullable=False),
    sa.Column('anomaly_type', sa.Enum('duplicate_payment', 'unexpected_pay_increase', 'abnormal_deduction', 'recent_bank_change', 'post_termination_payment', 'invalid_net_gross_ratio', name='anomalytype', native_enum=False), nullable=False),
    sa.Column('injection_details', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('payment_id', 'anomaly_type', name='uq_payment_anomaly_type')
    )
    op.create_table('investigations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('alert_id', sa.String(length=36), nullable=False),
    sa.Column('outcome', sa.Enum('confirmed_issue', 'legitimate_payment', 'needs_information', name='investigationoutcome', native_enum=False), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('investigator', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['alert_id'], ['anomaly_alerts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_investigations_alert_created', 'investigations', ['alert_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_investigations_alert_created', table_name='investigations')
    op.drop_table('investigations')
    op.drop_table('anomaly_labels')
    op.drop_index('ix_alerts_status_risk', table_name='anomaly_alerts')
    op.drop_index('ix_alerts_payment', table_name='anomaly_alerts')
    op.drop_table('anomaly_alerts')
    op.drop_index('ix_payments_employee_run', table_name='payments')
    op.drop_index('ix_payments_bank_token', table_name='payments')
    op.drop_table('payments')
    op.drop_index('ix_bank_account_employee_effective', table_name='bank_account_history')
    op.drop_table('bank_account_history')
    op.drop_table('payroll_runs')
    op.drop_table('model_runs')
    op.drop_index('ix_employees_department_grade', table_name='employees')
    op.drop_table('employees')
    # ### end Alembic commands ###

